### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by sharonmleon** [omeka/theme-freedom#1]
Please test the Omeka Classic version of Freedom, paying special attention to the configuration options and some of the more popular plugins: (Exhibit Builder, Simple Pages, Geolocation, Contribution, Collection Tree, SimpleVocab, Search By Metadata).

**Comment by katknow** [comment]
I still need to check on the plugins, but in terms of configuration here's what I've found so far: 

- Child pages disappear from navigation in Revolution when switched to full height column.
- I can't seem to make the banner appear no matter what I do to all the various settings.
- Under the homepage configuration it asks about the Main Featured Selection twice:
![image](https://github.com/omeka/theme-freedom/assets/84726696/b28f1c2d-fb8f-403f-8d1c-5a6f57afe45a)

- Where should the homepage intro background appear? I'm not seeing it, but I'm also not sure I understand where it should be.
- Under "Single Item Layout," changing to two columns makes the media disappear.

**Comment by katknow** [comment]
I'm not sure what the line is for in front of the footer content: 
![image](https://github.com/omeka/theme-freedom/assets/84726696/79533968-cc6c-4581-9ccf-5b4236f29cf3)
I notice there are two lines when there nav bar is also being shown, so I wonder if it has something to do with that.

I'm filling in the the "Recent Records" section but nothing seems to be happening.

When all of the "Records Tags" are unchecked all tags disappear, yet regardless of what is checked all three kinds of tags appear.

The spacing seems a bit off on the Contribution page, especially between the "Browse" button and "Title":
![Screenshot 2023-10-15 at 21-08-38 Contribute · Exploring D C](https://github.com/omeka/theme-freedom/assets/84726696/84278639-6841-4be5-872f-62c1ef66c0d0)

I tried to install Simple Vocab to test, but I can't get it to appear in the menu.

Exhibit Builder, Simple Pages, Geolocation, Collection Tree all seem to be working fine and look okay.

**Comment by allanaaa** [comment]
I'm not clear on the logo instructions (210x60px). That's only for when the menu and logo are inline, right? I wonder if we can toggle the interface instructions based on that dropdown selection. 

I'm not sure the banner recommendation (1280x560) is great either. Surely we want people to upload wider images that won't get stretched when the browser window is wider than 1280?

Note also that the default footer text is "Powered by Omeka S" 😬

I would include some explanatory text about the footer layout - "Content will appear in 1, 2, or 3 columns with dividing lines depending on how many of the following fields you use" or something.

**Comment by allanaaa** [comment]
The menu, when full-width, has these focus underlines that are just a bit off to me. 

When a menu item is two lines of text, the line goes across the full width of the li. 
![menu2](https://github.com/omeka/theme-freedom/assets/28012148/eb528772-44d3-4131-94fe-97d53ce76125)

But when a menu item is one line, it just shows up like an underline on the text (i.e. it's not the full width of the li). 
![menu1](https://github.com/omeka/theme-freedom/assets/28012148/b5f28ad1-e545-4725-a4b7-10236f43ab9c)

Can we make these match, one way or the other?

**Comment by allanaaa** [comment]
The image derivatives you're showing on the browse pages look really fuzzy. My square thumbnails are set to 200x200, and you're displaying 312x312 or something. Is there a setting to change that? I see they do resize a small amount when the window resizes, but I don't want to see anything stretched up at all. 
I realize I could resize all my thumbnails for use on this site, but that seems drastic. Or at least we should include instructions on how to do that, whatever the maximum size is that you might want to display.

**Comment by sharonmleon** [comment]
@nelsonamaya82 I assigned you to this issue and added you to the Team Omeka core, so you should now be getting alerts.

**Comment by allanaaa** [comment]
Can you turn off the "Item" tag that shows on the Browse Items page? Ditto the "Collection" that shows on the Browse Collections page.'

![item](https://github.com/omeka/theme-freedom/assets/28012148/a7d5c9f3-1db5-49a1-af17-ca8292147e80)

**Comment by allanaaa** [comment]
Also we should probably limit the number of tags that show on the Browse pages, some of them have A LOT.
![toomanytags](https://github.com/omeka/theme-freedom/assets/28012148/5833ef5a-db9d-4ca5-a2f1-18cb5f1e512d)

**Comment by nelsonamaya82** [comment]
@katknow I tested the "Recent Records" section and it works fine, here's a screenshot:
![image](https://github.com/omeka/theme-freedom/assets/6953921/7bb089c1-106a-4b7f-971f-b149f58a6110)

I installed the Simple Vocab plugin and it works fine, I can see it in the menu:
![image](https://github.com/omeka/theme-freedom/assets/6953921/d21e0748-54da-4efa-ad0b-a2c20ad27d5e)
![image](https://github.com/omeka/theme-freedom/assets/6953921/782e2a6b-c538-4d5e-9784-ea540055a33f)

@allanaaa the logo instructions (210x60px) are general, no matter the header layout. Anyway this is just a recommended size).

Fuzzy images: I was using th wrong image size but it's fixed now. Look way better.
Limit the number of tags: I added a new option to the Theme Settings page in order to set the max number of tags to display. In case an item has more tags than the max number, there will be a link "...more" next to the tags to indicate the user there are more (hidden) tags. When clicked, it should go to the record show page and scroll automatically to the "Tags" section, where the user can see all the tags:
![image](https://github.com/omeka/theme-freedom/assets/6953921/8b184446-9d78-466e-a582-6c942c2f6786)

**Comment by allanaaa** [comment]
I'm getting this when I have multiple levels of menu items: 


https://github.com/omeka/theme-freedom/assets/28012148/ae803060-bb0d-48b3-950c-dc564c3d89be

**Comment by allanaaa** [comment]
The advanced search page seems to have slightly different padding than the other pages: 


https://github.com/omeka/theme-freedom/assets/28012148/95debff3-9089-4f0c-9f8f-72426b8017d9

**Comment by allanaaa** [comment]
Also, the Contribution page (from the Contribution plugin) is also misaligned compared to other pages. I imagine this is just a form padding issue. 

http://dev.omeka.org/amayer/amayer-c/omeka/contribution

But Contact Us (from the Simple Contact Form plugin) looks fine:

http://dev.omeka.org/amayer/amayer-c/omeka/contact

**Comment by allanaaa** [comment]
On a collections page like this:

http://dev.omeka.org/amayer/amayer-c/omeka/collections/show/99

What determines how many items are shown? I can't count how many are on this page but it would be nice to cut it off at 10-20.

**Comment by allanaaa** [comment]
For collections that are hierarchical using the Collection Tree plugin, I wonder if the collection view page could show the bullet list of subcollections higher up? That might be a plugin question instead of a theme question. I'm not sure how we do it on other themes. 

http://dev.omeka.org/amayer/amayer-c/omeka/collections/show/1

**Comment by katknow** [comment]
Recent Records is now working fine for me as well, so not sure what the issue was before.

I will say that I'm not having the same menu issue if that helps narrow down potential problems.

My collections do seem to be cutting off at 10 with a "View all X items" link at the bottom.

However, on the browse collections page I'm now having a problem where one of the containers goes down into the buttons to tab between pages:

![image](https://github.com/omeka/theme-freedom/assets/84726696/af2bedc2-f66e-4be3-8f87-3a5e209341d6)

This is issue is not replicated on any of my other browse pages.

**Comment by nelsonamaya82** [comment]
@allanaaa:

- The Advanced Search page doesn't have a different padding, but the main container is narrower intentionally in order to keep both the page title and the form aligned (as the form is narrower than the default content). This is how it looks like on a bigger screen:

https://github.com/omeka/theme-freedom/assets/6953921/b2959c1e-1b2b-410f-9b4c-326111b20491

Same case with Contribution page. However I think the Contact Us page should be narrower, just like the other form pages (Advanced Search and Contribution). In general terms, narrower forms are more user friendly, but please let me know your thoughts.

- What determines how many items are shown? I'm not really sure as I can't find any code in the frontend related to this quantity in this specific page, I think it's something from the backend. The page you sent as an example has 50 items. Please check in the dashboard, under Appearance -> Settings how many items you have in "Results Per Page". That's the only field that comes to my mind that might control that. If not, I'd have to ask Jim or John.

- For collections that are hierarchical using the Collection Tree plugin, this functionality comes directly from the plugin. It works like this on other themes too.

The rest of the issues are fixed and merged into the `master` branch.

@katknow the screenshot you sent is from a local environment? It seems like it's not properly built as I don't see the buttons icons and the menu items text are not correctly aligned (they should be vertically centered). If it's from a local site, please pull the `master` branch again and build the theme assets.

**Comment by allanaaa** [comment]
> In general terms, narrower forms are more user friendly, but please let me know your thoughts.

I want the page title to be in the same spot on every page, rather than aligned with the content. Happy to be outvoted on this, though, if anyone else wants to chime in.

> That's the only field that comes to my mind that might control that. If not, I'd have to ask Jim or John.

If you could make that a separate setting, or just hard-code it down to fewer, that would be great. I have it at 50 for "browse items" and "browse collections" results per page, but when looking at a collection's view page by itself, I would want that way lower, since you can then link to see the results on their own.

**Comment by allanaaa** [comment]
Thank you for fixing the menu! Looks great.

**Comment by nelsonamaya82** [comment]
@allanaaa I've just pushed the adjustment to the title alignment to the `master` branch.

So this is how it looked like before:
![image](https://github.com/omeka/theme-freedom/assets/6953921/4924b808-cc91-4d24-abfe-96b8a7e219e7)

and this how it's now:
![image](https://github.com/omeka/theme-freedom/assets/6953921/f070b3f7-568f-4d25-9b07-9f05cc2a1a2e)

Regarding the custom number of items in a collection show page, I talked with John and we'll check the option to put this in the core's appearance settings so you just could always set it and it would apply for every theme (it's better to not work around it in the theme but do it in the core so it's there in a newer release). I'll keep you posted on this.

**Comment by nelsonamaya82** [comment]
@allanaaa @katknow please let me know if you found anything else, or if you think we're ready to release this theme. Thanks!

**Comment by nelsonamaya82** [comment]
@allanaaa the option to set a custom number of items in a collection show page will be addressed here: https://github.com/omeka/Omeka/issues/1016

**Comment by allanaaa** [comment]
Looks great, I'm just going to look at it on my phone.

**Comment by allanaaa** [comment]
It really looks fantastic on mobile, I'm happy to see this released.

One thing that you can mull over at your leisure, no rush for this release and might necessitate a new release for S as well - can we give users two colour choices in the theme settings? So they can change the dark blue footer / nav colour, in future releases?

**Comment by nelsonamaya82** [comment]
Thanks @allanaaa and @katknow, sounds good! I'll start working on the release. And yes, adding the option to select the dark color sounds like a good addition to the themes, I'm creating a ticket to add it later.
